### ISSUE TITLE
字幕表示.exaの折り返す幅が機能しない

### ISSUE THREAD

**Issue by nazonoSAUNA** [oov/aviutl_psdtoolkit#105]
キャッシュではない方の字幕表示.exaで折り返す幅が機能しなかったので確認していたところexaの問題でした。

max = 800    ,-- 折り返す幅
正しくはwidth = と思われます

**Comment by oov** [comment]
ご報告ありがとうございます。
開発段階ではパラメーター名を `max` にしていたので、名称変更時の作業漏れと思われます。
