### ISSUE TITLE
exaファイルの余計なヘッダーを無くす

### ISSUE THREAD

**Issue by nazonoSAUNA** [oov/aviutl_psdtoolkit#107]
```
[vo]
length=64
camera=0
```
の部分が不要な気がしました。
この部分を無くすことで、デフォルトの図形やテキストなどを追加する時と同じようにタイムラインの表示倍率に依存した長さのオブジェクトが置かれるようになり、特別理由が無ければそちらの方が良いと思います

エイリアス作成時にこの部分があるかどうかの違いとしては、次のどちらの操作でエイリアスを作成したかによります
・タイムラインのオブジェクトを右クリック->エイリアスを作成
・設定ダイアログで右クリック->設定の保存->現在の設定でエイリアスを作成する

**Comment by oov** [comment]
なるほど、それは良いですね！
次回リリース時にやってみようと思います。
ありがとうございます。

**Comment by oov** [comment]
v0.2.0beta67 で反映されたものがリリースされました。
アドバイスありがとうございました。
