### ISSUE TITLE
小数点の入ったlabファイルが読み込めない

### ISSUE THREAD

**Issue by mikan-megane** [oov/aviutl_psdtoolkit#63]
タイミング情報に小数点以下の桁が入ったlabファイルが読み込めず、エラーが出てしまう。
labファイルはCeVIO CS6から出力されたものを使用。

![image](https://user-images.githubusercontent.com/3056109/53286120-1c966900-37ad-11e9-8caf-be27bfeab874.png)

```lab
683100000 683800000 t
683800000 684552631.578947 a
684552631.578947 685125000 p
```

**Comment by oov** [comment]
CeVIO が出力する lab ファイルは時間の単位に 1/10,000,000 秒というかなり細かいものを採用しているので整数しか現れないのが正解なのかと思っていたんですが、hts_engine API のソースコードを軽く調査してみた限り `atof` でパースされるようなので、これを受け入れられるようにしておくのが仕様的にも正しいようです。
