### ISSUE TITLE
PSDファイルが見つからないときプロジェクトファイルのディレクトリを探して欲しい

### ISSUE THREAD

**Issue by PUCHIRYUU** [oov/aviutl_psdtoolkit#75]
PSDファイルの指定パスに該当ファイルが見つからないとき、プロジェクトファイル(.aup)のあるディレクトリ内の同名のファイルを探すようにしていただきたいです。

制作時点で使ったPSDファイルを、プロジェクトファイルや他の素材と一緒に１つのディレクトリに収めておくことで、位置に依存しないバックアップ環境を構築します。（拡張編集にて読み込んだファイルが見つからないときは、プロジェクトファイルのディレクトリを参照するため）

現在、PSDオブジェクト上で、パスを削ってPSDファイルのファイル名のみを指定した場合"PSDToolKit.auf"の場所を読むようなので、現在はこれを利用して擬似的にバックアップ環境を構築していますが、プロジェクト作成のたびにPSDファイルをバージョンアップしていくにつれて、Aviutl本体のディレクトリが散らかってきたので・・・。ご検討よろしくおねがいします。

**Comment by oov** [comment]
対応検討します。
拡張編集の挙動に合わせるのは合理的で良さそうに思えます。

**Comment by oov** [comment]
PSD ファイルと WAVE ファイルについて、見つからない場合にプロジェクトファイルが存在するフォルダーから探す機能を追加しました。
本家機能と異なり拡張編集内でのファイル参照先が変わることはないので（変えるのが難しい）、元の位置にファイルが復活するとまたそちらを読み込みに行ってしまいます。
