### ISSUE TITLE
Krita で作成した PSD 用の PFV ファイルの挙動がおかしい

### ISSUE THREAD

**Issue by TeeeJey** [oov/aviutl_psdtoolkit#78]
一昨日こちらのPSD Toolの存在を知り、あまりの機能の充実度に驚き、即導入させていただいたTeeeJeyと申します。PSD Toolでお気に入りの表情を登録する所まではサクサク進んだのですが、いざAviutlにPFVを読み込んで編集するぞ！という段階になり問題に直面したので、質問させていただきます。

-------------------------------------

使用バージョン：最新の　0.2beta49
Aviutl v1.00
拡張編集 v0.92

行った操作：
1. ニコニコに上がっている解説動画：https://www.nicovideo.jp/watch/sm28712861
及びPSD Tool Reference Manualを参考にしながらAviutlにPSD Tool Kitを導入
2. PSD Toolの独自拡張機能を利用したPSDファイルをKritaで作成
3. PSD Toolに読み込ませ、お気に入りを複数作成（特にフォルダー分けはしていないため、構造は至ってシンプル）
4. お気に入りをPFVファイル形式で出力
5. PSDファイルとPFVファイルを両方選択して同時にAviutlへD&D
6. PSD Tool Kit ウィンドウを開き、「シンプルV」と「お気に入り」の使用を試みる

症状：
1. PSD Tool Kitウィンドウ内でシンプルVのスライダーを動かしても何も変化が起きず、ドロップダウンメニューを選ぶと、なぜか項目と項目の間に空白の行があり、PSD Toolで登録したはずの項目の半分しか表示されない（添付画像01,02,03参照）。
2. PSD Tool Kitウィンドウ内でお気に入りを選択すると、全てのラジオボタンがOFFになり、のっぺらぼうになる（添付画像04,05参照）。PSD Toolでは、普通にお気に入りの表情をワンクリックで切り替えられていたので、恐らくPFVファイル自体は問題ない（添付画像06参照）。

添付画像：
![PSDToolKit_v0 2beta49_画像01](https://user-images.githubusercontent.com/31401641/92991978-3976c680-f522-11ea-9843-409c688d80a2.PNG)

![PSDToolKit_v0 2beta49_画像02](https://user-images.githubusercontent.com/31401641/92991989-5612fe80-f522-11ea-957f-13105036dc74.PNG)

![PSDToolKit_v0 2beta49_画像03](https://user-images.githubusercontent.com/31401641/92991991-5ad7b280-f522-11ea-9518-61f12acf1571.PNG)

![PSDToolKit_v0 2beta49_画像04](https://user-images.githubusercontent.com/31401641/92991992-5e6b3980-f522-11ea-9ce5-40a6875e4235.PNG)

![PSDToolKit_v0 2beta49_画像05](https://user-images.githubusercontent.com/31401641/92991996-61662a00-f522-11ea-8d68-568061e1fa6c.PNG)

![PSDToolKit_v0 2beta49_画像06](https://user-images.githubusercontent.com/31401641/92991998-64f9b100-f522-11ea-9cfa-a4749e1246dc.PNG)
---------------------------------------
Reference Manual通りに導入したつもりですが、やはりPSD Tool Kit自体の導入が正しく行われていないのでしょうか・・・？お忙しい中恐縮ですが、何か解決策があれば教えていただけると幸いです。

**Comment by oov** [comment]
挙動だけを見る限りではバグっぽく見えます。
今の情報だとまだ原因がわからないので、ひとまず PFV ファイルを作成するために使用したブラウザについて教えていただきたいです。
また、可能であれば PSD ファイルと PFV ファイルの内容をメールアドレス `ilovevipper@gmail.com` までお送りいただけますでしょうか？
こちらでも同じファイルを読み込んだ上で検証してみたいと思います。
ご迷惑をおかけして申し訳ございません。

**Comment by oov** [comment]
メールありがとうございます。
ファイルを確認したところ原因がわかりました。

Krita で作成した PSD ファイルではレイヤーの名前の最後に「テキストの終端」を表すマークのようなものが不正に入っており、それへの対処方法がブラウザー版の PSDTool と AviUtl 版の PSDToolKit で異なっているのが原因で起こっている問題でした。
ご迷惑をおかけして申し訳ございません。

将来的にはこのバグを修正する予定ですが、今すぐPSDファイルを使えるようにするには以下のような方法があります。

#### STEP1: PFV ファイルを使える状態に修正する

PFV ファイルをテキストエディターで開いて、存在するすべての「%00」を除去して上書き保存します。  
このように改変すると PFV ファイルは PSDToolKit ではうまく動くようになりますが、PSDTool 上では上手く動かなくなります。

#### STEP2: PSD ファイルを別のソフトで編集する

FireAlpaca など同様の問題が起こらないソフトで PSD ファイルを開いて、全てのレイヤー名を１字削って上書き保存します。  
（レイヤー名の最後のスペースが「%00」に該当する不正な文字で、ソフトによっては上書きだけで消えるものもあるかも）

この方法で編集すると、未改変の PFV ファイルは恐らく PSDToolKit でも PSDTool でも動かなくなります。  
STEP1 の手順で対処した PFV ファイルならどちらでも正しく動くようになると思います。

**Comment by TeeeJey** [comment]
教えていただいた通り、PFVファイルの%00を全て除去したところ、しっかり動作致しました。ありがとうございます！

しばらくは、PFVファイルのバックアップを取り、テキストエディタで開く　→　内容をMicrosoft Wordに一度コピー　→　「置換」機能で%00をNullと置換　→　今度はWordからテキストエディタへ内容をコピー

という方法で使って行こうと思います。今後の更新も楽しみにしつつ、ずっと愛用させていただきます。

**Comment by oov** [comment]
PSDToolKit v0.2beta50 で、この問題に対して修正を施しました。  
PSDTool と同じように `%00` を除去していない、元々の PFV ファイルで動くようになっているはずです。  
動作確認していただけましたら幸いです。

逆に、取り除いたファイルだと PSD に格納されているレイヤー名と異なるため、現在では動かなくなりました。
お手数ですがバージョンアップの際にはバックアップされている PFV ファイルに差し替えてお使いください。
よろしくお願いいたします。

**Comment by oov** [comment]
10日以上経過しているので close します。

**Comment by TeeeJey** [comment]
Oov様

せっかく修正いただいたのにも関わらず、通知を完全に見落としておりました。

早速明日バージョンアップしてみたいと思います! ご親切にどうもありがとうございました。

TeeeJey

2020年9月30日(水) 5:55 Masanobu YOSHIOKA <notifications@github.com>:
